INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('fidel', 'villanueva@icloud.com', '43535336', '0', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('carlos', 'carlos@icloud.com', '35366', '0', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Angel Fuentes', 'villanueva@icloud.com', '43535336', '1', 'fig_1_08.png');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Tim Baser', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Angel Fuentes', 'villanueva@icloud.com', '43535336', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Tim Baser', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Garcia Mendez', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Ana Palacios', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Karla Villanueva', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Javier Fuentes', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Ricardo Valenz', 'carlos@icloud.com', '35366', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Test Usuario', 'test@gmail.com', '3536363', '1', 'default.jpg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('prima', 'prima@pe.com', '4353536', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('fdgdg', 'dgdgdg', 'dgdgd', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('eret', 'ttet', '35353', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('liz', 'liz@gmail.com', '999999', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('rettet', 'tetete', '3353536', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('dwerrwr', 'dwdwdw', '42424224244', '1', null);
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('ff', 'fsfsf', 'wrwrwr', '1', 'yov.svg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Fidel Villanueva Delgado', 'fvillanueva@icloud.com', '2324242', '1', 'Heroku.png');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Fidel 2', 'villa@ilocud,com', '242424', '1', 'init.svg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Test svg', 'villanueva@gmail.com', '3353535', '1', 'team.svg');
INSERT INTO development.usuarios (name, email, phone, status, image) VALUES ('Fidel Villanueva', 'villa@gmail.com', '2242535252', '1', 'init.svg');